### ISSUE TITLE
what does OpenAI Style Endpoints mean?

### ISSUE THREAD

**Issue by chymian** [DevXT-LLC/ezlocalai#6]
@Josh-XT found your comment [here](https://github.com/daveshap/ACE_Framework/issues/141) and I'm curious - just creating a docker…

what openAI-API endpoints do you support? 
version 1.x.x?
functions?

**Comment by Josh-XT** [comment]
Hello! By OpenAI style, I mean that you can use the OpenAI Python module or any other software that uses OpenAI endpoints to point at this server to run through a local model of your choosing instead of OpenAI's servers or models.

Please see the [examples notebook here.](https://github.com/Josh-XT/Local-LLM/blob/main/examples.ipynb)
